# 服务端口号
server:
  port: 8761
spring:
  application:
    name: frank-eureka # 对外暴露的服务名称
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}@127.0.0.1:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false