# 服务端口号
server:
  port: 8002
  servlet:
    context-path: /user
spring:
  application:
    name: frank-user # 对外暴露的服务名称
#   Redis配置
  redis:
    database: 2
    host: 47.110.236.21
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  config:
    jwt:
      signing-key: frank-signing
      verifier-key: frank-verifier
#    安全配置
security:
  oauth2:
    client:
      client-id: user
      client-secret: user-frank-knDlT0NQHEfZVcoWjIV5rWawgVq8baao
      user-authorization-uri: http://localhost:8001/sso/oauth/authorize
      access-token-uri: http://localhost:8001/sso/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8001/sso/oauth/token_key
        key-value: 123456
    authorization:
      check-token-access: http://localhost:8001/sso/oauth/check_token

#注册中心配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到eureka服务器
    fetch-registry: true #是否可检索
    service-url:
      defaultZone: http://frank:eureka@localhost:8761/eureka/ #服务中心
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.frank.sso.model