# 服务端口号
server:
  port: 8001
  servlet:
    context-path: /sso

#spring 配置
spring:
  application:
    name: frank-sso # 对外暴露的服务名称

#  redis 配置
  redis:
    database: 2
    host: 47.110.236.21
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
#  数据库配置
  datasource:
    url: jdbc:mysql://47.110.236.21:3306/doudou?characterEncoding=UTF-8&useSSL=false
    username: doudou
    password: fu12071116045
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
    driver-class-name: com.mysql.jdbc.Driver
  config:
    jwt:
      signing-key: frank-signing

#注册中心配置
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true  #是否注册到eureka服务器
    fetch-registry: true        #是否可检索
    service-url:
      defaultZone: http://frank:eureka@127.0.0.1:8761/eureka/ #服务中心
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.frank.sso.model
