# 服务端口号
server:
  port: 8001
  servlet:
    context-path: /pjb
spring:
  application:
    name: frank-sso # 对外暴露的服务名称
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到eureka服务器
    fetch-registry: true #是否可检索
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务中心
