# 服务端口号
server:
  port: 8086
  servlet:
    context-path: /pan
spring:
  application:
    name: frank-pan # 对外暴露的服务名称
    redis:
      database: 2
      host: localhost
      port: 32768
      password: 1qaz@WSX
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 100ms
security:
  oauth2:
    client:
      client-id: pan
      client-secret: pan-frank-knDlT0NQHEfZVcoWjIV5rWawgVq8baao
      user-authorization-uri: http://localhost:8001/sso/oauth/authorize
      access-token-uri: http://localhost:8001/sso/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8001/sso/oauth/token_key
        key-value: 123456
#      id: pan
#      user-info-uri: pan
    authorization:
      check-token-access: http://localhost:8001/sso/oauth/check_token
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到eureka服务器
    fetch-registry: true #是否可检索
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务中心
